### ISSUE TITLE
是不是还没有开放呢？

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYDiversityLive_iOS#2]
WIKI没有任何资料。

**Comment by fpzeng** [comment]
已经开放了。我们直接写到readme.md里面了，如果有不清楚，需要进一步解释的，我们会写到wiki。欢迎持续关注。

**Comment by leewaycn** [comment]
下载的DEMO不能跑起来呢／

**Comment by qiujinWang** [comment]
人脸贴纸功能是不是还不开放呢？怎么找不到资料！

**Comment by qiujinWang** [comment]
ld: warning: directory not found for option '-L/libksygpulive/prebuilt/libs'
ld: library not found for -lPods-KSYFaceunityKitDemo
clang: error: linker command failed with exit code 1 (use -v to see invocation)


报错跑不起来啊！lPods-KSYFaceunityKitDemo这个文件没有找到！

**Comment by sunjian283019** [comment]
hi，@qiujinWang 这个问题我看wiki中写了解决的办法，这是因为pod的版本问题，在看一下我们的wiki呢
