### ISSUE TITLE
啥时候升级一下faceunity的DEMO。我现在用的是V2.0.0的SDK。

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYDiversityLive_iOS#4]
啥时候升级一下faceunity的DEMO。我现在用的是V2.0.0的SDK。

**Comment by fpzeng** [comment]
示例里面是1.9.4，直接换成2.0.0的libksygpulive没有问题的。

两者没有很强的版本依赖

**Comment by alanwang-dev** [comment]
@leewaycn faceunity 已更新至v3.2.4

**Comment by alanwang-dev** [comment]
@leewaycn faceunity demo 更新只v3.2.4，使用最新版库v2.0.3

**Comment by alanwang-dev** [comment]
faceunity demo 更新至v3.2.4，使用最新版库v2.0.3
