### ISSUE TITLE
集成faceunity的DEMO中，每选一次贴纸就增加一次资源占用，但并不释放。越选越大。

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYDiversityLive_iOS#5]
每个贴纸大概占用 40M ，所以。。你懂的。
我的程序要崩溃了。

**Comment by leewaycn** [comment]
添加贴纸是否是在同步线程中进行的。
我发现很容易崩溃。
当我改了可以释放资源后。
是不是在异步线程中调用了faceunity的 步骤。

**Comment by leewaycn** [comment]
#pragma -FUCameraDelegate
- (void)didOutputVideoSampleBuffer:(CMSampleBufferRef)sampleBuffer
{   // NSLog(@"%s",__func__);//这个会一直在调用的。

    if ([UIApplication sharedApplication].applicationState != UIApplicationStateActive) {
        return;
    }
    
    //如果当前环境中已存在EAGLContext，此步骤可省略，但必须要调用[EAGLContext setCurrentContext:curContext]函数。
    #warning 此步骤不可放在异步线程中执行
    [self setUpContext];
    
    //Faceunity初始化
    #warning 此步骤不可放在异步线程中执行

**Comment by alanwang-dev** [comment]
已于tag：faceUnity_3.2.4版本进行了修改，做了动态加载和释放贴纸，支持美颜和手势
