### ISSUE TITLE
接入face unity 发现贴纸不能动呀。这个怎么破。

### ISSUE THREAD

**Issue by leewaycn** [ksvc/KSYDiversityLive_iOS#6]
接入face unity 发现贴纸不能动呀。这个怎么破。 贴纸是硬生的固定。失去了原有的活动性。

**Comment by alanwang-dev** [comment]
FaceUnityFilter.m
FURenderer的方法renderPixelBuffer:withFrameId:items:itemCount:中frameId需要自增，添加上g_frame_id += 1;可解决

**Comment by leewaycn** [comment]
thx .done
