### ISSUE TITLE
把AgoraSDK升级到1.9版本后报错

### ISSUE THREAD

**Issue by hf20** [ksvc/KSYDiversityLive_iOS#7]
ld: warning: directory not found for option '-F../../../build'
ld: warning: object file (/Users/mac/Desktop/金山云/最新与声网连麦GIT/agoraRtc/demo/AgoraRtcEngineKit.framework/AgoraRtcEngineKit(libAgoraRTCEngine.a-arm64-master.o)) was built for newer iOS version (9.3) than being linked (8.0)
duplicate symbol _TypeNo in:
    /Users/mac/Desktop/金山云/最新与声网连麦GIT/agoraRtc/demo/videoprp.framework/videoprp(GPUImageNfls.o)
    /Users/mac/Desktop/金山云/最新与声网连麦GIT/agoraRtc/demo/videoprp.framework/videoprp(AgoraYuvGpuEnhancer.o)
ld: 1 duplicate symbol for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by fpzeng** [comment]
我们暂时不支持1.9.0的声网版本，请使用https://github.com/ksvc/KSYDiversityLive_iOS/releases/tag/agora_v1.1.1

* 声网SDK 版本：1.8.3
* libksygpulive版本：[2.0.1](https://github.com/ksvc/KSYLive_iOS/releases/tag/v2.0.1)

**Comment by yulin6666** [comment]
最近的版本已经支持1.9
